export const NOTEBOARD_WORLD_MIN_X = -4000;
export const NOTEBOARD_WORLD_MAX_X = 4000;
export const NOTEBOARD_WORLD_MIN_Y = -4000;
export const NOTEBOARD_WORLD_MAX_Y = 4000;

export const NOTEBOARD_WORLD_WIDTH =
  NOTEBOARD_WORLD_MAX_X - NOTEBOARD_WORLD_MIN_X;
export const NOTEBOARD_WORLD_HEIGHT =
  NOTEBOARD_WORLD_MAX_Y - NOTEBOARD_WORLD_MIN_Y;
