import {
  app,
  BrowserWindow,
  dialog,
  ipcMain,
  Menu,
  nativeImage,
  protocol,
  shell,
  type MenuItemConstructorOptions,
} from 'electron';
import {
  access,
  copyFile,
  mkdir,
  readdir,
  readFile,
  rename,
  stat,
  unlink,
  writeFile,
} from 'node:fs/promises';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { pathToFileURL } from 'node:url';
import type {
  CustomThemeDefinition,
  LaunchState,
  PersistedTreeState,
  ProjectStatusPayload,
  ProjectSnapshot,
  ProjectImageAsset,
  RecentProjectEntry,
  SavedImageAsset,
  UserSettings,
} from './shared/types';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const getTreeStatePath = (): string =>
  path.join(app.getPath('userData'), 'data', 'tree-state.json');
const getUserSettingsPath = (): string =>
  path.join(app.getPath('userData'), 'data', 'user-settings.json');
const getDataBackupDir = (): string => path.join(app.getPath('userData'), 'data', 'backups');
const getInstallConfigPath = (): string =>
  path.join(app.getPath('userData'), 'data', 'install-config.json');
const getDefaultWorkspaceRoot = (): string => path.join(app.getPath('userData'), 'workspace');
const getInstallerFallbackConfigPath = (): string => {
  const localAppData =
    process.env.LOCALAPPDATA ?? path.join(app.getPath('home'), 'AppData', 'Local');
  return path.join(localAppData, app.getName(), 'data', 'install-config.json');
};
const readInstallerWorkspaceRoot = (): string | null => {
  const candidates = [getInstallConfigPath(), getInstallerFallbackConfigPath()];
  for (const candidate of candidates) {
    try {
      if (!existsSync(candidate)) {
        continue;
      }
      const parsed = JSON.parse(readFileSync(candidate, 'utf8')) as {
        workspaceRoot?: unknown;
      };
      if (typeof parsed.workspaceRoot === 'string' && parsed.workspaceRoot.trim()) {
        return path.resolve(parsed.workspaceRoot.trim());
      }
    } catch {
      // Ignore malformed installer config and fall back to defaults.
    }
  }

  return null;
};
const getRecentProjectsPath = (): string =>
  path.join(app.getPath('userData'), 'data', 'recent-projects.json');
let resolvedWorkspaceRoot: string | null = null;

const getProjectWorkspaceRoot = (): string => {
  if (resolvedWorkspaceRoot) {
    return resolvedWorkspaceRoot;
  }

  resolvedWorkspaceRoot = path.resolve(readInstallerWorkspaceRoot() ?? getDefaultWorkspaceRoot());
  return resolvedWorkspaceRoot;
};

const isPermissionError = (error: unknown): boolean =>
  typeof error === 'object' &&
  error !== null &&
  'code' in error &&
  ((error as { code?: string }).code === 'EPERM' || (error as { code?: string }).code === 'EACCES');

const canWriteToWorkspaceRoot = async (candidate: string): Promise<boolean> => {
  try {
    await mkdir(candidate, { recursive: true });
    const probePath = path.join(candidate, '.testo-write-probe');
    await writeFile(probePath, 'ok');
    await unlink(probePath);
    return true;
  } catch (error: unknown) {
    if (isPermissionError(error)) {
      return false;
    }
    return false;
  }
};

const ensureWritableWorkspaceRoot = async (): Promise<string> => {
  const configured = readInstallerWorkspaceRoot();
  const fallback = getDefaultWorkspaceRoot();
  const candidates = [configured, fallback].filter((value): value is string => Boolean(value));
  const seen = new Set<string>();

  for (const candidate of candidates) {
    const normalized = path.resolve(candidate);
    if (seen.has(normalized)) {
      continue;
    }
    seen.add(normalized);
    if (await canWriteToWorkspaceRoot(normalized)) {
      resolvedWorkspaceRoot = normalized;
      return normalized;
    }
  }

  await mkdir(fallback, { recursive: true });
  resolvedWorkspaceRoot = path.resolve(fallback);
  return resolvedWorkspaceRoot;
};
const getProjectImageAssetsDir = (): string =>
  path.join(getProjectWorkspaceRoot(), 'project-assets', 'images');
const getProjectRootPath = (): string => path.resolve(getProjectWorkspaceRoot());
const normalizeRelativePath = (value: string): string => value.split(path.sep).join('/');
const getWindowIconPath = (): string => path.join(app.getAppPath(), 'images', 'icon.png');

type ProjectBundleV1 = {
  version: 1;
  exportedAt: number;
  treeState: PersistedTreeState | null;
  userSettings: UserSettings | null;
  images: Array<{
    relativePath: string;
    mimeType: string;
    dataBase64: string;
  }>;
};

type CustomThemeBundleV1 = {
  version: 1;
  exportedAt: number;
  theme: CustomThemeDefinition;
};

type RecentProjectsFile = {
  recentProjects: RecentProjectEntry[];
  lastActiveProjectPath: string | null;
};

const IMAGE_EXTENSIONS = ['png', 'jpg', 'jpeg', 'gif', 'webp', 'bmp', 'svg', 'avif'];
const PROJECT_SNAPSHOT_TIMEOUT_MS = 1600;
const MAX_RECENT_PROJECTS = 12;
const PRIMARY_PROJECT_EXTENSION = 'prjt';
const LEGACY_PROJECT_EXTENSION = 'testo';
const SKIP_SPLASH_QUERY_PARAM = 'skipSplashOnce';

type PendingSnapshotRequest = {
  senderId: number;
  resolve: (snapshot: ProjectSnapshot | null) => void;
  timeout: ReturnType<typeof setTimeout>;
};

let nextSnapshotRequestId = 1;
const pendingSnapshotRequests = new Map<number, PendingSnapshotRequest>();

const extensionFromMimeType = (mimeType: string): string => {
  const normalized = mimeType.toLowerCase();
  if (normalized === 'image/png') {
    return 'png';
  }
  if (normalized === 'image/jpeg' || normalized === 'image/jpg') {
    return 'jpg';
  }
  if (normalized === 'image/gif') {
    return 'gif';
  }
  if (normalized === 'image/webp') {
    return 'webp';
  }
  if (normalized === 'image/bmp') {
    return 'bmp';
  }
  if (normalized === 'image/svg+xml') {
    return 'svg';
  }
  if (normalized === 'image/avif') {
    return 'avif';
  }

  return 'png';
};

const fileExists = async (filePath: string): Promise<boolean> => {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
};

const sanitizeRecentProjects = (value: unknown): RecentProjectEntry[] => {
  if (!Array.isArray(value)) {
    return [];
  }

  const unique = new Map<string, RecentProjectEntry>();
  value.forEach((item) => {
    if (typeof item !== 'object' || item === null) {
      return;
    }

    const candidate = item as {
      filePath?: unknown;
      fileName?: unknown;
      lastOpenedAt?: unknown;
    };
    if (
      typeof candidate.filePath !== 'string' ||
      !candidate.filePath.trim() ||
      typeof candidate.fileName !== 'string' ||
      !candidate.fileName.trim() ||
      typeof candidate.lastOpenedAt !== 'number' ||
      !Number.isFinite(candidate.lastOpenedAt)
    ) {
      return;
    }

    const filePath = candidate.filePath.trim();
    const existing = unique.get(filePath);
    if (!existing || candidate.lastOpenedAt > existing.lastOpenedAt) {
      unique.set(filePath, {
        filePath,
        fileName: candidate.fileName.trim(),
        lastOpenedAt: candidate.lastOpenedAt,
      });
    }
  });

  return [...unique.values()]
    .sort((a, b) => b.lastOpenedAt - a.lastOpenedAt)
    .slice(0, MAX_RECENT_PROJECTS);
};

const loadRecentProjectsState = async (): Promise<RecentProjectsFile> => {
  const raw = await loadJsonWithBackup<Partial<RecentProjectsFile>>(getRecentProjectsPath());
  const recentProjects = sanitizeRecentProjects(raw?.recentProjects);
  const lastActiveProjectPath =
    typeof raw?.lastActiveProjectPath === 'string' && raw.lastActiveProjectPath.trim()
      ? raw.lastActiveProjectPath.trim()
      : null;
  return {
    recentProjects,
    lastActiveProjectPath,
  };
};

const saveRecentProjectsState = async (state: RecentProjectsFile): Promise<void> => {
  await safeWriteFile(getRecentProjectsPath(), JSON.stringify(state, null, 2));
};

const upsertRecentProject = (
  current: RecentProjectsFile,
  filePath: string,
  at: number,
): RecentProjectsFile => {
  const fileName = path.basename(filePath);
  const nextRecentProjects = sanitizeRecentProjects([
    { filePath, fileName, lastOpenedAt: at },
    ...current.recentProjects,
  ]);

  return {
    recentProjects: nextRecentProjects,
    lastActiveProjectPath: filePath,
  };
};

const removeRecentProjectPath = (
  current: RecentProjectsFile,
  filePath: string,
): RecentProjectsFile => ({
  recentProjects: current.recentProjects.filter((entry) => entry.filePath !== filePath),
  lastActiveProjectPath:
    current.lastActiveProjectPath === filePath ? null : current.lastActiveProjectPath,
});

const isThemeTokenName = (value: string): boolean =>
  /^--[a-z0-9-]+$/i.test(value.trim());

const isThemeTokenValue = (value: string): boolean => {
  const trimmed = value.trim();
  if (!trimmed || trimmed.length > 160) {
    return false;
  }
  if (/[{};]/.test(trimmed)) {
    return false;
  }
  return true;
};

const isAppTheme = (value: unknown): value is CustomThemeDefinition['baseTheme'] =>
  value === 'parchment' || value === 'midnight' || value === 'evergreen';

const parseCustomThemeBundle = (raw: string): CustomThemeDefinition | null => {
  const parsed = JSON.parse(raw) as Partial<CustomThemeBundleV1>;
  if (parsed.version !== 1 || typeof parsed.theme !== 'object' || parsed.theme === null) {
    return null;
  }

  const theme = parsed.theme as Partial<CustomThemeDefinition>;
  if (
    typeof theme.id !== 'string' ||
    !theme.id.trim() ||
    typeof theme.name !== 'string' ||
    !theme.name.trim() ||
    !isAppTheme(theme.baseTheme)
  ) {
    return null;
  }

  if (typeof theme.tokens !== 'object' || theme.tokens === null || Array.isArray(theme.tokens)) {
    return null;
  }

  const tokens = Object.fromEntries(
    Object.entries(theme.tokens as Record<string, unknown>).flatMap(
      ([tokenKey, tokenValue]): Array<[string, string]> => {
        if (
          isThemeTokenName(tokenKey) &&
          typeof tokenValue === 'string' &&
          isThemeTokenValue(tokenValue)
        ) {
          return [[tokenKey, tokenValue.trim()]];
        }
        return [];
      },
    ),
  );

  const createdAt =
    typeof theme.createdAt === 'number' && Number.isFinite(theme.createdAt)
      ? theme.createdAt
      : Date.now();
  const updatedAt =
    typeof theme.updatedAt === 'number' && Number.isFinite(theme.updatedAt)
      ? theme.updatedAt
      : createdAt;

  return {
    id: theme.id.trim(),
    name: theme.name.trim().slice(0, 64),
    baseTheme: theme.baseTheme,
    tokens,
    createdAt,
    updatedAt,
  };
};

const createBackupPath = (filePath: string): string => {
  const parsed = path.parse(filePath);
  return path.join(getDataBackupDir(), `${parsed.base}.${Date.now()}.bak`);
};

const maybeBackupFile = async (filePath: string): Promise<void> => {
  if (!(await fileExists(filePath))) {
    return;
  }
  const backupDir = getDataBackupDir();
  await mkdir(backupDir, { recursive: true });
  const backupPath = createBackupPath(filePath);
  await copyFile(filePath, backupPath);
};

const safeWriteFile = async (filePath: string, content: string | Uint8Array): Promise<void> => {
  const folderPath = path.dirname(filePath);
  await mkdir(folderPath, { recursive: true });
  await maybeBackupFile(filePath);
  const tempPath = `${filePath}.tmp`;
  await writeFile(tempPath, content);
  await rename(tempPath, filePath);
};

const findNewestBackup = async (filePath: string): Promise<string | null> => {
  const backupDir = getDataBackupDir();
  if (!(await fileExists(backupDir))) {
    return null;
  }
  const base = path.parse(filePath).base;
  const entries = await readdir(backupDir, { withFileTypes: true });
  const candidates = entries
    .filter((entry) => entry.isFile() && entry.name.startsWith(`${base}.`) && entry.name.endsWith('.bak'))
    .map((entry) => path.join(backupDir, entry.name));
  if (candidates.length === 0) {
    return null;
  }
  let newest: { filePath: string; mtime: number } | null = null;
  for (const candidate of candidates) {
    const metadata = await stat(candidate);
    if (!newest || metadata.mtimeMs > newest.mtime) {
      newest = {
        filePath: candidate,
        mtime: metadata.mtimeMs,
      };
    }
  }
  return newest?.filePath ?? null;
};

const loadJsonWithBackup = async <T>(filePath: string): Promise<T | null> => {
  try {
    const contents = await readFile(filePath, 'utf-8');
    return JSON.parse(contents) as T;
  } catch (error: unknown) {
    if (
      typeof error === 'object' &&
      error !== null &&
      'code' in error &&
      (error as { code?: string }).code === 'ENOENT'
    ) {
      return null;
    }

    const backupPath = await findNewestBackup(filePath);
    if (!backupPath) {
      throw error;
    }

    const backupContents = await readFile(backupPath, 'utf-8');
    return JSON.parse(backupContents) as T;
  }
};

const isImageFileName = (fileName: string): boolean => {
  const extension = path.extname(fileName).toLowerCase().slice(1);
  return IMAGE_EXTENSIONS.includes(extension);
};

const toAssetUrl = (relativePath: string): string => {
  const encodedRelativePath = normalizeRelativePath(relativePath)
    .split('/')
    .map((segment) => encodeURIComponent(segment))
    .join('/');
  return `testo-asset://${encodedRelativePath}`;
};

const resolveImageAssetPath = (relativePath: string): string | null => {
  const projectRoot = getProjectRootPath();
  const imageRoot = path.resolve(getProjectImageAssetsDir());
  const absolutePath = path.resolve(projectRoot, relativePath);
  const relativeFromImageRoot = path.relative(imageRoot, absolutePath);
  if (
    !relativeFromImageRoot ||
    relativeFromImageRoot.startsWith('..') ||
    path.isAbsolute(relativeFromImageRoot)
  ) {
    return null;
  }
  return absolutePath;
};

const saveImageAsset = async (input: {
  bytes: Uint8Array;
  mimeType: string;
}): Promise<SavedImageAsset> => {
  if (!input || !(input.bytes instanceof Uint8Array) || input.bytes.length === 0) {
    throw new Error('Invalid image payload.');
  }

  const imageDir = getProjectImageAssetsDir();
  await mkdir(imageDir, { recursive: true });

  const buffer = Buffer.from(input.bytes);
  const hash = createHash('sha256').update(buffer).digest('hex');
  const desiredExt = extensionFromMimeType(input.mimeType);

  let existingFileName: string | null = null;
  for (const ext of IMAGE_EXTENSIONS) {
    const candidate = `${hash}.${ext}`;
    const candidatePath = path.join(imageDir, candidate);
    if (await fileExists(candidatePath)) {
      existingFileName = candidate;
      break;
    }
  }

  const fileName = existingFileName ?? `${hash}.${desiredExt}`;
  const absolutePath = path.join(imageDir, fileName);

  if (!existingFileName) {
    try {
      await writeFile(absolutePath, buffer, { flag: 'wx' });
    } catch (error: unknown) {
      if (
        typeof error === 'object' &&
        error !== null &&
        'code' in error &&
        (error as { code?: string }).code !== 'EEXIST'
      ) {
        throw error;
      }
    }
  }

  const relativePath = normalizeRelativePath(path.relative(getProjectRootPath(), absolutePath));

  return {
    absolutePath,
    relativePath,
    assetUrl: toAssetUrl(relativePath),
    fileUrl: pathToFileURL(absolutePath).toString(),
    deduplicated: Boolean(existingFileName),
  };
};

protocol.registerSchemesAsPrivileged([
  {
    scheme: 'testo-asset',
    privileges: {
      standard: true,
      secure: true,
      supportFetchAPI: true,
      corsEnabled: true,
    },
  },
]);

const registerAssetProtocol = (): void => {
  protocol.registerFileProtocol('testo-asset', (request, callback) => {
    try {
      const requestedUrl = new URL(request.url);
      const rawRelativePath = `${requestedUrl.hostname}${requestedUrl.pathname}`;
      const decodedRelativePath = decodeURIComponent(rawRelativePath).replace(/^[/\\]+/, '');
      const projectRoot = getProjectRootPath();
      const absolutePath = path.resolve(projectRoot, decodedRelativePath);
      const relativeFromRoot = path.relative(projectRoot, absolutePath);
      if (
        !relativeFromRoot ||
        relativeFromRoot.startsWith('..') ||
        path.isAbsolute(relativeFromRoot)
      ) {
        callback({ error: -10 });
        return;
      }
      const normalized = normalizeRelativePath(relativeFromRoot).toLowerCase();
      if (!normalized.startsWith('project-assets/images/')) {
        callback({ error: -10 });
        return;
      }

      callback({ path: absolutePath });
    } catch {
      callback({ error: -324 });
    }
  });
};

const listImageAssets = async (): Promise<ProjectImageAsset[]> => {
  const imageDir = getProjectImageAssetsDir();
  await mkdir(imageDir, { recursive: true });
  const entries = await readdir(imageDir, { withFileTypes: true });
  const assets: ProjectImageAsset[] = [];

  for (const entry of entries) {
    if (!entry.isFile() || !isImageFileName(entry.name)) {
      continue;
    }

    const absolutePath = path.join(imageDir, entry.name);
    const metadata = await stat(absolutePath);
    const relativePath = normalizeRelativePath(path.relative(getProjectRootPath(), absolutePath));
    const image = nativeImage.createFromPath(absolutePath);
    const size = image.getSize();

    assets.push({
      absolutePath,
      relativePath,
      assetUrl: toAssetUrl(relativePath),
      fileUrl: pathToFileURL(absolutePath).toString(),
      width: Math.max(1, size.width || 1),
      height: Math.max(1, size.height || 1),
      sizeBytes: metadata.size,
      updatedAt: metadata.mtimeMs,
    });
  }

  assets.sort((a, b) => b.updatedAt - a.updatedAt);
  return assets;
};

const deleteImageAsset = async (relativePath: string): Promise<void> => {
  const normalized = normalizeRelativePath(relativePath).replace(/^[/\\]+/, '');
  if (!normalized || !normalized.toLowerCase().startsWith('project-assets/images/')) {
    throw new Error('Invalid image asset path.');
  }

  const absolutePath = resolveImageAssetPath(normalized);
  if (!absolutePath) {
    throw new Error('Invalid image asset path.');
  }

  try {
    await unlink(absolutePath);
  } catch (error: unknown) {
    if (
      typeof error === 'object' &&
      error !== null &&
      'code' in error &&
      (error as { code?: string }).code === 'ENOENT'
    ) {
      return;
    }
    throw error;
  }
};

const removeFileIfExists = async (filePath: string): Promise<void> => {
  try {
    await unlink(filePath);
  } catch (error: unknown) {
    if (
      typeof error === 'object' &&
      error !== null &&
      'code' in error &&
      (error as { code?: string }).code === 'ENOENT'
    ) {
      return;
    }
    throw error;
  }
};

const clearCurrentProjectData = async (): Promise<void> => {
  await removeFileIfExists(getTreeStatePath());
  await removeFileIfExists(getUserSettingsPath());

  const imageDir = getProjectImageAssetsDir();
  await mkdir(imageDir, { recursive: true });
  const entries = await readdir(imageDir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.isFile()) {
      await unlink(path.join(imageDir, entry.name));
    }
  }
};

const loadTreeState = async (): Promise<PersistedTreeState | null> => {
  const filePath = getTreeStatePath();
  return loadJsonWithBackup<PersistedTreeState>(filePath);
};

const saveTreeState = async (state: PersistedTreeState): Promise<void> => {
  const filePath = getTreeStatePath();
  await safeWriteFile(filePath, JSON.stringify(state, null, 2));
};

const loadUserSettings = async (): Promise<UserSettings | null> => {
  const filePath = getUserSettingsPath();
  return loadJsonWithBackup<UserSettings>(filePath);
};

const saveUserSettings = async (settings: UserSettings): Promise<void> => {
  const filePath = getUserSettingsPath();
  await safeWriteFile(filePath, JSON.stringify(settings, null, 2));
};

const exportCustomThemeToFile = async (
  inputTheme: CustomThemeDefinition,
): Promise<boolean> => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  if (!focusedWindow) {
    return false;
  }

  const result = await dialog.showSaveDialog(focusedWindow, {
    title: 'Export Custom Theme',
    defaultPath: `${inputTheme.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '') || 'custom-theme'}.testo-theme.json`,
    filters: [
      { name: 'Testo Theme', extensions: ['testo-theme', 'json'] },
      { name: 'JSON', extensions: ['json'] },
    ],
  });

  if (result.canceled || !result.filePath) {
    return false;
  }

  const bundle: CustomThemeBundleV1 = {
    version: 1,
    exportedAt: Date.now(),
    theme: inputTheme,
  };
  await safeWriteFile(result.filePath, JSON.stringify(bundle, null, 2));
  return true;
};

const importCustomThemeFromFile = async (): Promise<CustomThemeDefinition | null> => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  if (!focusedWindow) {
    return null;
  }

  const result = await dialog.showOpenDialog(focusedWindow, {
    title: 'Import Custom Theme',
    properties: ['openFile'],
    filters: [
      { name: 'Testo Theme', extensions: ['testo-theme', 'json'] },
      { name: 'JSON', extensions: ['json'] },
    ],
  });
  if (result.canceled || result.filePaths.length === 0) {
    return null;
  }

  const filePath = result.filePaths[0];
  const content = await readFile(filePath, 'utf8');
  return parseCustomThemeBundle(content);
};

const mimeTypeFromExtension = (extension: string): string => {
  const normalized = extension.toLowerCase();
  if (normalized === '.png') {
    return 'image/png';
  }
  if (normalized === '.jpg' || normalized === '.jpeg') {
    return 'image/jpeg';
  }
  if (normalized === '.gif') {
    return 'image/gif';
  }
  if (normalized === '.webp') {
    return 'image/webp';
  }
  if (normalized === '.bmp') {
    return 'image/bmp';
  }
  if (normalized === '.svg') {
    return 'image/svg+xml';
  }
  if (normalized === '.avif') {
    return 'image/avif';
  }
  return 'application/octet-stream';
};

const readProjectBundle = async (filePath: string): Promise<ProjectBundleV1> => {
  const content = await readFile(filePath, 'utf-8');
  const parsed = JSON.parse(content) as Partial<ProjectBundleV1>;
  if (parsed.version !== 1 || !Array.isArray(parsed.images)) {
    throw new Error('Invalid project file format.');
  }
  return {
    version: 1,
    exportedAt: typeof parsed.exportedAt === 'number' ? parsed.exportedAt : Date.now(),
    treeState: parsed.treeState ?? null,
    userSettings: parsed.userSettings ?? null,
    images: parsed.images
      .filter(
        (item) =>
          item &&
          typeof item.relativePath === 'string' &&
          typeof item.mimeType === 'string' &&
          typeof item.dataBase64 === 'string',
      )
      .map((item) => ({
        relativePath: item.relativePath,
        mimeType: item.mimeType,
        dataBase64: item.dataBase64,
      })),
  };
};

const writeProjectBundle = async (filePath: string): Promise<void> => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  const snapshot = focusedWindow ? await requestRendererProjectSnapshot(focusedWindow) : null;

  const [treeState, userSettings, assets] = await Promise.all([
    snapshot ? Promise.resolve(snapshot.treeState) : loadTreeState(),
    snapshot ? Promise.resolve(snapshot.userSettings) : loadUserSettings(),
    listImageAssets(),
  ]);

  const images: ProjectBundleV1['images'] = [];
  for (const asset of assets) {
    const bytes = await readFile(asset.absolutePath);
    images.push({
      relativePath: asset.relativePath,
      mimeType: mimeTypeFromExtension(path.extname(asset.absolutePath)),
      dataBase64: bytes.toString('base64'),
    });
  }

  const bundle: ProjectBundleV1 = {
    version: 1,
    exportedAt: Date.now(),
    treeState,
    userSettings,
    images,
  };

  await safeWriteFile(filePath, JSON.stringify(bundle));
};

const requestRendererProjectSnapshot = async (
  window: BrowserWindow,
): Promise<ProjectSnapshot | null> => {
  const requestId = nextSnapshotRequestId++;

  return new Promise((resolve) => {
    const timeout = setTimeout(() => {
      const pending = pendingSnapshotRequests.get(requestId);
      if (!pending) {
        return;
      }
      pendingSnapshotRequests.delete(requestId);
      pending.resolve(null);
    }, PROJECT_SNAPSHOT_TIMEOUT_MS);

    pendingSnapshotRequests.set(requestId, {
      senderId: window.webContents.id,
      resolve,
      timeout,
    });

    window.webContents.send('project:request-snapshot', requestId);
  });
};

const reloadSkippingSplashOnce = async (window: BrowserWindow): Promise<boolean> => {
  if (window.isDestroyed()) {
    return false;
  }

  try {
    const currentUrl = window.webContents.getURL();
    if (!currentUrl) {
      return false;
    }
    const nextUrl = new URL(currentUrl);
    nextUrl.searchParams.set(SKIP_SPLASH_QUERY_PARAM, '1');
    await window.loadURL(nextUrl.toString());
    return true;
  } catch {
    return false;
  }
};

const applyProjectBundle = async (bundle: ProjectBundleV1): Promise<void> => {
  if (bundle.treeState) {
    await saveTreeState(bundle.treeState);
  } else {
    await removeFileIfExists(getTreeStatePath());
  }
  if (bundle.userSettings) {
    await saveUserSettings(bundle.userSettings);
  } else {
    await removeFileIfExists(getUserSettingsPath());
  }

  const imageDir = getProjectImageAssetsDir();
  await mkdir(imageDir, { recursive: true });
  const existing = await readdir(imageDir, { withFileTypes: true });
  for (const entry of existing) {
    if (entry.isFile()) {
      await unlink(path.join(imageDir, entry.name));
    }
  }

  for (const image of bundle.images) {
    const normalized = normalizeRelativePath(image.relativePath).replace(/^[/\\]+/, '');
    const resolved = resolveImageAssetPath(normalized);
    if (!resolved) {
      continue;
    }
    const folderPath = path.dirname(resolved);
    await mkdir(folderPath, { recursive: true });
    const bytes = Buffer.from(image.dataBase64, 'base64');
    await writeFile(resolved, bytes);
  }
};

let activeProjectFilePath: string | null = null;
let mainWindowRef: BrowserWindow | null = null;

type ReleaseLookupResult = {
  repo: string;
  latestVersion: string;
  latestTag: string;
  downloadUrl: string;
};

const UPDATE_REPO_SLUG = (process.env.TESTO_UPDATE_REPO ?? '').trim();

const normalizeVersionTag = (value: string): string =>
  value.trim().replace(/^v/i, '').split('-')[0];

const compareVersions = (left: string, right: string): number => {
  const leftParts = normalizeVersionTag(left)
    .split('.')
    .map((part) => Number.parseInt(part, 10));
  const rightParts = normalizeVersionTag(right)
    .split('.')
    .map((part) => Number.parseInt(part, 10));

  const maxParts = Math.max(leftParts.length, rightParts.length);
  for (let i = 0; i < maxParts; i += 1) {
    const l = Number.isFinite(leftParts[i]) ? leftParts[i] : 0;
    const r = Number.isFinite(rightParts[i]) ? rightParts[i] : 0;
    if (l > r) {
      return 1;
    }
    if (l < r) {
      return -1;
    }
  }

  return 0;
};

const fetchLatestGithubRelease = async (repo: string): Promise<ReleaseLookupResult> => {
  const endpoint = `https://api.github.com/repos/${repo}/releases/latest`;
  const response = await fetch(endpoint, {
    headers: {
      Accept: 'application/vnd.github+json',
      'User-Agent': `${app.getName()}/${app.getVersion()}`,
    },
  });

  if (!response.ok) {
    throw new Error(`GitHub releases request failed with ${response.status}.`);
  }

  const payload = (await response.json()) as {
    tag_name?: unknown;
    html_url?: unknown;
  };
  if (typeof payload.tag_name !== 'string' || !payload.tag_name.trim()) {
    throw new Error('Latest GitHub release is missing tag_name.');
  }

  const latestVersion = normalizeVersionTag(payload.tag_name);
  if (!latestVersion) {
    throw new Error('Latest GitHub release tag is invalid.');
  }

  const downloadUrl =
    typeof payload.html_url === 'string' && payload.html_url.trim()
      ? payload.html_url
      : `https://github.com/${repo}/releases/latest`;

  return {
    repo,
    latestVersion,
    latestTag: payload.tag_name.trim(),
    downloadUrl: downloadUrl.trim(),
  };
};

const checkForGithubUpdates = async (manual: boolean): Promise<void> => {
  const currentVersion = normalizeVersionTag(app.getVersion());
  const focusedWindow = BrowserWindow.getFocusedWindow() ?? mainWindowRef;

  if (!UPDATE_REPO_SLUG) {
    if (manual) {
      emitProjectStatus(focusedWindow, {
        status: 'info',
        action: 'update',
        filePath: null,
        message:
          'Updates are not configured. Set TESTO_UPDATE_REPO to your GitHub repo (owner/name).',
      });
    }
    return;
  }

  try {
    const latest = await fetchLatestGithubRelease(UPDATE_REPO_SLUG);
    const comparison = compareVersions(latest.latestVersion, currentVersion);

    if (comparison > 0) {
      emitProjectStatus(focusedWindow, {
        status: 'info',
        action: 'update',
        filePath: null,
        message: `Update available: v${latest.latestVersion} (current v${currentVersion}).`,
      });

      if (manual && focusedWindow) {
        const result = await dialog.showMessageBox(focusedWindow, {
          type: 'info',
          buttons: ['Open Download Page', 'Later'],
          defaultId: 0,
          cancelId: 1,
          title: 'Update Available',
          message: `Version ${latest.latestTag} is available.`,
          detail: `Current version: v${currentVersion}\nLatest version: v${latest.latestVersion}`,
        });

        if (result.response === 0) {
          await shell.openExternal(latest.downloadUrl);
        }
      }
      return;
    }

    if (manual) {
      emitProjectStatus(focusedWindow, {
        status: 'success',
        action: 'update',
        filePath: null,
        message: `You're on the latest version (v${currentVersion}).`,
      });
    }
  } catch (error: unknown) {
    if (!manual) {
      return;
    }

    emitProjectStatus(focusedWindow, {
      status: 'error',
      action: 'update',
      filePath: null,
      message: `Update check failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
    });
  }
};

const getLaunchState = async (): Promise<LaunchState> => {
  const recentState = await loadRecentProjectsState();
  const existingEntries: RecentProjectEntry[] = [];
  for (const entry of recentState.recentProjects) {
    if (await fileExists(entry.filePath)) {
      existingEntries.push(entry);
    }
  }

  const hasLastActive =
    recentState.lastActiveProjectPath && (await fileExists(recentState.lastActiveProjectPath));
  const nextState: RecentProjectsFile = {
    recentProjects: existingEntries,
    lastActiveProjectPath: hasLastActive ? recentState.lastActiveProjectPath : null,
  };

  const changed =
    nextState.recentProjects.length !== recentState.recentProjects.length ||
    nextState.lastActiveProjectPath !== recentState.lastActiveProjectPath;
  if (changed) {
    await saveRecentProjectsState(nextState);
  }

  return {
    recentProjects: nextState.recentProjects,
    lastActiveProjectPath: nextState.lastActiveProjectPath,
  };
};

const emitProjectStatus = (
  window: BrowserWindow | null,
  payload: Omit<ProjectStatusPayload, 'at'>,
): void => {
  if (!window || window.isDestroyed()) {
    return;
  }
  const statusPayload: ProjectStatusPayload = {
    ...payload,
    at: Date.now(),
  };
  window.webContents.send('menu:project-status', statusPayload);
};

const markProjectAsRecent = async (filePath: string): Promise<void> => {
  const current = await loadRecentProjectsState();
  const next = upsertRecentProject(current, filePath, Date.now());
  await saveRecentProjectsState(next);
};

const removeRecentProject = async (filePath: string): Promise<void> => {
  const current = await loadRecentProjectsState();
  const next = removeRecentProjectPath(current, filePath);
  await saveRecentProjectsState(next);
};

const saveProjectFileAs = async (): Promise<boolean> => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  if (!focusedWindow) {
    return false;
  }

  const result = await dialog.showSaveDialog(focusedWindow, {
    title: 'Save Project File',
    defaultPath:
      activeProjectFilePath ?? path.join(getProjectRootPath(), `untitled.${PRIMARY_PROJECT_EXTENSION}`),
    filters: [
      {
        name: 'Testo Project',
        extensions: [PRIMARY_PROJECT_EXTENSION],
      },
    ],
  });
  if (result.canceled || !result.filePath) {
    return false;
  }

  try {
    await writeProjectBundle(result.filePath);
    activeProjectFilePath = result.filePath;
    await markProjectAsRecent(result.filePath);
    emitProjectStatus(focusedWindow, {
      status: 'success',
      action: 'save-as',
      filePath: result.filePath,
      message: `Saved project as ${path.basename(result.filePath)}.`,
    });
    return true;
  } catch (error: unknown) {
    emitProjectStatus(focusedWindow, {
      status: 'error',
      action: 'save-as',
      filePath: result.filePath,
      message: `Save As failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
    });
    return false;
  }
};

const saveProjectFile = async (): Promise<boolean> => {
  if (!activeProjectFilePath) {
    return saveProjectFileAs();
  }
  const focusedWindow = BrowserWindow.getFocusedWindow();
  try {
    await writeProjectBundle(activeProjectFilePath);
    await markProjectAsRecent(activeProjectFilePath);
    emitProjectStatus(focusedWindow, {
      status: 'success',
      action: 'save',
      filePath: activeProjectFilePath,
      message: `Saved ${path.basename(activeProjectFilePath)}.`,
    });
    return true;
  } catch (error: unknown) {
    emitProjectStatus(focusedWindow, {
      status: 'error',
      action: 'save',
      filePath: activeProjectFilePath,
      message: `Save failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
    });
    return false;
  }
};

const openProjectByPath = async (
  filePath: string,
  focusedWindow: BrowserWindow,
): Promise<boolean> => {
  try {
    await ensureWritableWorkspaceRoot();
    const bundle = await readProjectBundle(filePath);
    await applyProjectBundle(bundle);
    activeProjectFilePath = filePath;
    await markProjectAsRecent(filePath);
    emitProjectStatus(focusedWindow, {
      status: 'success',
      action: 'open',
      filePath,
      message: `Opened ${path.basename(filePath)}.`,
    });
    const reloaded = await reloadSkippingSplashOnce(focusedWindow);
    if (!reloaded) {
      focusedWindow.reload();
    }
    return true;
  } catch (error: unknown) {
    await removeRecentProject(filePath);
    emitProjectStatus(focusedWindow, {
      status: 'error',
      action: 'open',
      filePath,
      message: `Open failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
    });
    return false;
  }
};

const openProjectFile = async (): Promise<boolean> => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  if (!focusedWindow) {
    return false;
  }

  const result = await dialog.showOpenDialog(focusedWindow, {
    title: 'Open Project File',
    properties: ['openFile'],
    filters: [
      {
        name: 'Testo Project',
        extensions: [PRIMARY_PROJECT_EXTENSION, LEGACY_PROJECT_EXTENSION],
      },
    ],
  });
  if (result.canceled || result.filePaths.length === 0) {
    return false;
  }

  return openProjectByPath(result.filePaths[0], focusedWindow);
};

const openRecentProject = async (filePath: string): Promise<boolean> => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  if (!focusedWindow) {
    return false;
  }

  if (!filePath.trim()) {
    return false;
  }

  return openProjectByPath(filePath.trim(), focusedWindow);
};

const createNewProject = async (): Promise<boolean> => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  if (!focusedWindow) {
    return false;
  }

  const result = await dialog.showMessageBox(focusedWindow, {
    type: 'question',
    buttons: ['Create New Project', 'Cancel'],
    defaultId: 1,
    cancelId: 1,
    title: 'Create New Project',
    message: 'Create a new project and clear the current local project data?',
    detail: 'This clears current tree, settings, and cached images for this workspace.',
  });

  if (result.response !== 0) {
    return false;
  }

  try {
    await clearCurrentProjectData();
    activeProjectFilePath = null;
    await saveRecentProjectsState({
      ...(await loadRecentProjectsState()),
      lastActiveProjectPath: null,
    });
    emitProjectStatus(focusedWindow, {
      status: 'success',
      action: 'new',
      filePath: null,
      message: 'Created a new project workspace.',
    });
    const reloaded = await reloadSkippingSplashOnce(focusedWindow);
    if (!reloaded) {
      focusedWindow.reload();
    }
    return true;
  } catch (error: unknown) {
    emitProjectStatus(focusedWindow, {
      status: 'error',
      action: 'new',
      filePath: null,
      message: `New project failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
    });
    return false;
  }
};

ipcMain.handle('tree:load', async () => loadTreeState());
ipcMain.handle('tree:save', async (_event, state: PersistedTreeState) => {
  await saveTreeState(state);
});
ipcMain.handle('settings:load', async () => loadUserSettings());
ipcMain.handle('settings:save', async (_event, settings: UserSettings) => {
  await saveUserSettings(settings);
});
ipcMain.handle(
  'assets:save-image',
  async (
    _event,
    input: {
      bytes: Uint8Array;
      mimeType: string;
    },
  ) => saveImageAsset(input),
);
ipcMain.handle('assets:list-images', async () => listImageAssets());
ipcMain.handle('assets:delete-image', async (_event, relativePath: string) => {
  await deleteImageAsset(relativePath);
});
ipcMain.handle('themes:export-custom', async (_event, theme: CustomThemeDefinition) =>
  exportCustomThemeToFile(theme),
);
ipcMain.handle('themes:import-custom', async () => importCustomThemeFromFile());
ipcMain.handle('project:launch-state', async () => getLaunchState());
ipcMain.handle('project:open-dialog', async () => openProjectFile());
ipcMain.handle('project:open-recent', async (_event, filePath: string) =>
  openRecentProject(filePath),
);
ipcMain.handle('project:new', async () => createNewProject());
ipcMain.handle('app:check-updates', async () => {
  await checkForGithubUpdates(true);
});
ipcMain.on(
  'project:snapshot-response',
  (
    event,
    payload:
      | {
          requestId?: unknown;
          snapshot?: unknown;
        }
      | undefined,
  ) => {
    if (!payload || typeof payload.requestId !== 'number') {
      return;
    }

    const pending = pendingSnapshotRequests.get(payload.requestId);
    if (!pending || pending.senderId !== event.sender.id) {
      return;
    }

    clearTimeout(pending.timeout);
    pendingSnapshotRequests.delete(payload.requestId);

    const snapshotCandidate = payload.snapshot as Partial<ProjectSnapshot> | null | undefined;
    if (
      snapshotCandidate &&
      typeof snapshotCandidate === 'object' &&
      typeof snapshotCandidate.treeState === 'object' &&
      snapshotCandidate.treeState !== null &&
      typeof snapshotCandidate.userSettings === 'object' &&
      snapshotCandidate.userSettings !== null
    ) {
      pending.resolve({
        treeState: snapshotCandidate.treeState as PersistedTreeState,
        userSettings: snapshotCandidate.userSettings as UserSettings,
      });
      return;
    }

    pending.resolve(null);
  },
);

const openSettingsFromMenu = (): void => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  if (!focusedWindow) {
    return;
  }
  focusedWindow.webContents.send('menu:open-settings');
};

const buildAppMenu = (): void => {
  const viewMenu: MenuItemConstructorOptions['submenu'] = app.isPackaged
    ? [
        { role: 'resetZoom' },
        { role: 'zoomIn' },
        { role: 'zoomOut' },
        { type: 'separator' },
        { role: 'togglefullscreen' },
      ]
    : [
        { role: 'reload' },
        { role: 'forceReload' },
        { role: 'toggleDevTools' },
        { type: 'separator' },
        { role: 'resetZoom' },
        { role: 'zoomIn' },
        { role: 'zoomOut' },
        { type: 'separator' },
        { role: 'togglefullscreen' },
      ];

  const template: MenuItemConstructorOptions[] = [
    {
      label: 'File',
      submenu: [
        {
          label: 'New Project',
          accelerator: 'CmdOrCtrl+N',
          click: () => {
            void createNewProject();
          },
        },
        { type: 'separator' },
        {
          label: 'Open Project File...',
          accelerator: 'CmdOrCtrl+O',
          click: () => {
            void openProjectFile();
          },
        },
        {
          label: 'Save Project File',
          accelerator: 'CmdOrCtrl+S',
          click: () => {
            void saveProjectFile();
          },
        },
        {
          label: 'Save Project File As...',
          accelerator: 'CmdOrCtrl+Shift+S',
          click: () => {
            void saveProjectFileAs();
          },
        },
        { type: 'separator' },
        {
          label: 'Settings',
          accelerator: 'CmdOrCtrl+,',
          click: openSettingsFromMenu,
        },
        { type: 'separator' },
        { role: 'quit' },
      ],
    },
    { role: 'editMenu' },
    {
      label: 'View',
      submenu: viewMenu,
    },
    { role: 'windowMenu' },
    {
      role: 'help',
      submenu: [
        {
          label: 'Check for Updates...',
          click: () => {
            void checkForGithubUpdates(true);
          },
        },
      ],
    },
  ];

  Menu.setApplicationMenu(Menu.buildFromTemplate(template));
};

const createWindow = (): BrowserWindow => {
  const windowIcon = nativeImage.createFromPath(getWindowIconPath());
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 1080,
    width: 1920,
    icon: windowIcon.isEmpty() ? undefined : windowIcon,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      devTools: !app.isPackaged,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  if (!app.isPackaged) {
    mainWindow.webContents.openDevTools();
  }

  return mainWindow;
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  const windowIcon = nativeImage.createFromPath(getWindowIconPath());
  if (process.platform === 'darwin' && !windowIcon.isEmpty()) {
    app.dock.setIcon(windowIcon);
  }

  void (async () => {
    try {
      await ensureWritableWorkspaceRoot();
      const launchState = await getLaunchState();
      activeProjectFilePath = launchState.lastActiveProjectPath;
    } catch {
      activeProjectFilePath = null;
    }
    registerAssetProtocol();
    buildAppMenu();
    mainWindowRef = createWindow();
    setTimeout(() => {
      void checkForGithubUpdates(false);
    }, 1200);
  })();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    mainWindowRef = createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
