import {
  app,
  BrowserWindow,
  dialog,
  ipcMain,
  Menu,
  nativeImage,
  protocol,
  type MenuItemConstructorOptions,
} from 'electron';
import {
  access,
  copyFile,
  mkdir,
  readdir,
  readFile,
  rename,
  stat,
  unlink,
  writeFile,
} from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { pathToFileURL } from 'node:url';
import type {
  PersistedTreeState,
  ProjectStatusPayload,
  ProjectSnapshot,
  ProjectImageAsset,
  SavedImageAsset,
  UserSettings,
} from './shared/types';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const getTreeStatePath = (): string =>
  path.join(app.getPath('userData'), 'data', 'tree-state.json');
const getUserSettingsPath = (): string =>
  path.join(app.getPath('userData'), 'data', 'user-settings.json');
const getDataBackupDir = (): string => path.join(app.getPath('userData'), 'data', 'backups');
const getProjectImageAssetsDir = (): string =>
  path.join(process.cwd(), 'project-assets', 'images');
const getProjectRootPath = (): string => path.resolve(process.cwd());
const normalizeRelativePath = (value: string): string => value.split(path.sep).join('/');

type ProjectBundleV1 = {
  version: 1;
  exportedAt: number;
  treeState: PersistedTreeState | null;
  userSettings: UserSettings | null;
  images: Array<{
    relativePath: string;
    mimeType: string;
    dataBase64: string;
  }>;
};

const IMAGE_EXTENSIONS = ['png', 'jpg', 'jpeg', 'gif', 'webp', 'bmp', 'svg', 'avif'];
const PROJECT_SNAPSHOT_TIMEOUT_MS = 1600;

type PendingSnapshotRequest = {
  senderId: number;
  resolve: (snapshot: ProjectSnapshot | null) => void;
  timeout: ReturnType<typeof setTimeout>;
};

let nextSnapshotRequestId = 1;
const pendingSnapshotRequests = new Map<number, PendingSnapshotRequest>();

const extensionFromMimeType = (mimeType: string): string => {
  const normalized = mimeType.toLowerCase();
  if (normalized === 'image/png') {
    return 'png';
  }
  if (normalized === 'image/jpeg' || normalized === 'image/jpg') {
    return 'jpg';
  }
  if (normalized === 'image/gif') {
    return 'gif';
  }
  if (normalized === 'image/webp') {
    return 'webp';
  }
  if (normalized === 'image/bmp') {
    return 'bmp';
  }
  if (normalized === 'image/svg+xml') {
    return 'svg';
  }
  if (normalized === 'image/avif') {
    return 'avif';
  }

  return 'png';
};

const fileExists = async (filePath: string): Promise<boolean> => {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
};

const createBackupPath = (filePath: string): string => {
  const parsed = path.parse(filePath);
  return path.join(getDataBackupDir(), `${parsed.base}.${Date.now()}.bak`);
};

const maybeBackupFile = async (filePath: string): Promise<void> => {
  if (!(await fileExists(filePath))) {
    return;
  }
  const backupDir = getDataBackupDir();
  await mkdir(backupDir, { recursive: true });
  const backupPath = createBackupPath(filePath);
  await copyFile(filePath, backupPath);
};

const safeWriteFile = async (filePath: string, content: string | Uint8Array): Promise<void> => {
  const folderPath = path.dirname(filePath);
  await mkdir(folderPath, { recursive: true });
  await maybeBackupFile(filePath);
  const tempPath = `${filePath}.tmp`;
  await writeFile(tempPath, content);
  await rename(tempPath, filePath);
};

const findNewestBackup = async (filePath: string): Promise<string | null> => {
  const backupDir = getDataBackupDir();
  if (!(await fileExists(backupDir))) {
    return null;
  }
  const base = path.parse(filePath).base;
  const entries = await readdir(backupDir, { withFileTypes: true });
  const candidates = entries
    .filter((entry) => entry.isFile() && entry.name.startsWith(`${base}.`) && entry.name.endsWith('.bak'))
    .map((entry) => path.join(backupDir, entry.name));
  if (candidates.length === 0) {
    return null;
  }
  let newest: { filePath: string; mtime: number } | null = null;
  for (const candidate of candidates) {
    const metadata = await stat(candidate);
    if (!newest || metadata.mtimeMs > newest.mtime) {
      newest = {
        filePath: candidate,
        mtime: metadata.mtimeMs,
      };
    }
  }
  return newest?.filePath ?? null;
};

const loadJsonWithBackup = async <T>(filePath: string): Promise<T | null> => {
  try {
    const contents = await readFile(filePath, 'utf-8');
    return JSON.parse(contents) as T;
  } catch (error: unknown) {
    if (
      typeof error === 'object' &&
      error !== null &&
      'code' in error &&
      (error as { code?: string }).code === 'ENOENT'
    ) {
      return null;
    }

    const backupPath = await findNewestBackup(filePath);
    if (!backupPath) {
      throw error;
    }

    const backupContents = await readFile(backupPath, 'utf-8');
    return JSON.parse(backupContents) as T;
  }
};

const isImageFileName = (fileName: string): boolean => {
  const extension = path.extname(fileName).toLowerCase().slice(1);
  return IMAGE_EXTENSIONS.includes(extension);
};

const toAssetUrl = (relativePath: string): string => {
  const encodedRelativePath = normalizeRelativePath(relativePath)
    .split('/')
    .map((segment) => encodeURIComponent(segment))
    .join('/');
  return `testo-asset://${encodedRelativePath}`;
};

const resolveImageAssetPath = (relativePath: string): string | null => {
  const projectRoot = getProjectRootPath();
  const imageRoot = path.resolve(getProjectImageAssetsDir());
  const absolutePath = path.resolve(projectRoot, relativePath);
  const relativeFromImageRoot = path.relative(imageRoot, absolutePath);
  if (
    !relativeFromImageRoot ||
    relativeFromImageRoot.startsWith('..') ||
    path.isAbsolute(relativeFromImageRoot)
  ) {
    return null;
  }
  return absolutePath;
};

const saveImageAsset = async (input: {
  bytes: Uint8Array;
  mimeType: string;
}): Promise<SavedImageAsset> => {
  if (!input || !(input.bytes instanceof Uint8Array) || input.bytes.length === 0) {
    throw new Error('Invalid image payload.');
  }

  const imageDir = getProjectImageAssetsDir();
  await mkdir(imageDir, { recursive: true });

  const buffer = Buffer.from(input.bytes);
  const hash = createHash('sha256').update(buffer).digest('hex');
  const desiredExt = extensionFromMimeType(input.mimeType);

  let existingFileName: string | null = null;
  for (const ext of IMAGE_EXTENSIONS) {
    const candidate = `${hash}.${ext}`;
    const candidatePath = path.join(imageDir, candidate);
    if (await fileExists(candidatePath)) {
      existingFileName = candidate;
      break;
    }
  }

  const fileName = existingFileName ?? `${hash}.${desiredExt}`;
  const absolutePath = path.join(imageDir, fileName);

  if (!existingFileName) {
    try {
      await writeFile(absolutePath, buffer, { flag: 'wx' });
    } catch (error: unknown) {
      if (
        typeof error === 'object' &&
        error !== null &&
        'code' in error &&
        (error as { code?: string }).code !== 'EEXIST'
      ) {
        throw error;
      }
    }
  }

  const relativePath = normalizeRelativePath(path.relative(process.cwd(), absolutePath));

  return {
    absolutePath,
    relativePath,
    assetUrl: toAssetUrl(relativePath),
    fileUrl: pathToFileURL(absolutePath).toString(),
    deduplicated: Boolean(existingFileName),
  };
};

protocol.registerSchemesAsPrivileged([
  {
    scheme: 'testo-asset',
    privileges: {
      standard: true,
      secure: true,
      supportFetchAPI: true,
      corsEnabled: true,
    },
  },
]);

const registerAssetProtocol = (): void => {
  protocol.registerFileProtocol('testo-asset', (request, callback) => {
    try {
      const requestedUrl = new URL(request.url);
      const rawRelativePath = `${requestedUrl.hostname}${requestedUrl.pathname}`;
      const decodedRelativePath = decodeURIComponent(rawRelativePath).replace(/^[/\\]+/, '');
      const projectRoot = getProjectRootPath();
      const absolutePath = path.resolve(projectRoot, decodedRelativePath);
      const relativeFromRoot = path.relative(projectRoot, absolutePath);
      if (
        !relativeFromRoot ||
        relativeFromRoot.startsWith('..') ||
        path.isAbsolute(relativeFromRoot)
      ) {
        callback({ error: -10 });
        return;
      }
      const normalized = normalizeRelativePath(relativeFromRoot).toLowerCase();
      if (!normalized.startsWith('project-assets/images/')) {
        callback({ error: -10 });
        return;
      }

      callback({ path: absolutePath });
    } catch {
      callback({ error: -324 });
    }
  });
};

const listImageAssets = async (): Promise<ProjectImageAsset[]> => {
  const imageDir = getProjectImageAssetsDir();
  await mkdir(imageDir, { recursive: true });
  const entries = await readdir(imageDir, { withFileTypes: true });
  const assets: ProjectImageAsset[] = [];

  for (const entry of entries) {
    if (!entry.isFile() || !isImageFileName(entry.name)) {
      continue;
    }

    const absolutePath = path.join(imageDir, entry.name);
    const metadata = await stat(absolutePath);
    const relativePath = normalizeRelativePath(path.relative(process.cwd(), absolutePath));
    const image = nativeImage.createFromPath(absolutePath);
    const size = image.getSize();

    assets.push({
      absolutePath,
      relativePath,
      assetUrl: toAssetUrl(relativePath),
      fileUrl: pathToFileURL(absolutePath).toString(),
      width: Math.max(1, size.width || 1),
      height: Math.max(1, size.height || 1),
      sizeBytes: metadata.size,
      updatedAt: metadata.mtimeMs,
    });
  }

  assets.sort((a, b) => b.updatedAt - a.updatedAt);
  return assets;
};

const deleteImageAsset = async (relativePath: string): Promise<void> => {
  const normalized = normalizeRelativePath(relativePath).replace(/^[/\\]+/, '');
  if (!normalized || !normalized.toLowerCase().startsWith('project-assets/images/')) {
    throw new Error('Invalid image asset path.');
  }

  const absolutePath = resolveImageAssetPath(normalized);
  if (!absolutePath) {
    throw new Error('Invalid image asset path.');
  }

  try {
    await unlink(absolutePath);
  } catch (error: unknown) {
    if (
      typeof error === 'object' &&
      error !== null &&
      'code' in error &&
      (error as { code?: string }).code === 'ENOENT'
    ) {
      return;
    }
    throw error;
  }
};

const removeFileIfExists = async (filePath: string): Promise<void> => {
  try {
    await unlink(filePath);
  } catch (error: unknown) {
    if (
      typeof error === 'object' &&
      error !== null &&
      'code' in error &&
      (error as { code?: string }).code === 'ENOENT'
    ) {
      return;
    }
    throw error;
  }
};

const clearCurrentProjectData = async (): Promise<void> => {
  await removeFileIfExists(getTreeStatePath());
  await removeFileIfExists(getUserSettingsPath());

  const imageDir = getProjectImageAssetsDir();
  await mkdir(imageDir, { recursive: true });
  const entries = await readdir(imageDir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.isFile()) {
      await unlink(path.join(imageDir, entry.name));
    }
  }
};

const loadTreeState = async (): Promise<PersistedTreeState | null> => {
  const filePath = getTreeStatePath();
  return loadJsonWithBackup<PersistedTreeState>(filePath);
};

const saveTreeState = async (state: PersistedTreeState): Promise<void> => {
  const filePath = getTreeStatePath();
  await safeWriteFile(filePath, JSON.stringify(state, null, 2));
};

const loadUserSettings = async (): Promise<UserSettings | null> => {
  const filePath = getUserSettingsPath();
  return loadJsonWithBackup<UserSettings>(filePath);
};

const saveUserSettings = async (settings: UserSettings): Promise<void> => {
  const filePath = getUserSettingsPath();
  await safeWriteFile(filePath, JSON.stringify(settings, null, 2));
};

const mimeTypeFromExtension = (extension: string): string => {
  const normalized = extension.toLowerCase();
  if (normalized === '.png') {
    return 'image/png';
  }
  if (normalized === '.jpg' || normalized === '.jpeg') {
    return 'image/jpeg';
  }
  if (normalized === '.gif') {
    return 'image/gif';
  }
  if (normalized === '.webp') {
    return 'image/webp';
  }
  if (normalized === '.bmp') {
    return 'image/bmp';
  }
  if (normalized === '.svg') {
    return 'image/svg+xml';
  }
  if (normalized === '.avif') {
    return 'image/avif';
  }
  return 'application/octet-stream';
};

const readProjectBundle = async (filePath: string): Promise<ProjectBundleV1> => {
  const content = await readFile(filePath, 'utf-8');
  const parsed = JSON.parse(content) as Partial<ProjectBundleV1>;
  if (parsed.version !== 1 || !Array.isArray(parsed.images)) {
    throw new Error('Invalid project file format.');
  }
  return {
    version: 1,
    exportedAt: typeof parsed.exportedAt === 'number' ? parsed.exportedAt : Date.now(),
    treeState: parsed.treeState ?? null,
    userSettings: parsed.userSettings ?? null,
    images: parsed.images
      .filter(
        (item) =>
          item &&
          typeof item.relativePath === 'string' &&
          typeof item.mimeType === 'string' &&
          typeof item.dataBase64 === 'string',
      )
      .map((item) => ({
        relativePath: item.relativePath,
        mimeType: item.mimeType,
        dataBase64: item.dataBase64,
      })),
  };
};

const writeProjectBundle = async (filePath: string): Promise<void> => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  const snapshot = focusedWindow ? await requestRendererProjectSnapshot(focusedWindow) : null;

  const [treeState, userSettings, assets] = await Promise.all([
    snapshot ? Promise.resolve(snapshot.treeState) : loadTreeState(),
    snapshot ? Promise.resolve(snapshot.userSettings) : loadUserSettings(),
    listImageAssets(),
  ]);

  const images: ProjectBundleV1['images'] = [];
  for (const asset of assets) {
    const bytes = await readFile(asset.absolutePath);
    images.push({
      relativePath: asset.relativePath,
      mimeType: mimeTypeFromExtension(path.extname(asset.absolutePath)),
      dataBase64: bytes.toString('base64'),
    });
  }

  const bundle: ProjectBundleV1 = {
    version: 1,
    exportedAt: Date.now(),
    treeState,
    userSettings,
    images,
  };

  await safeWriteFile(filePath, JSON.stringify(bundle));
};

const requestRendererProjectSnapshot = async (
  window: BrowserWindow,
): Promise<ProjectSnapshot | null> => {
  const requestId = nextSnapshotRequestId++;

  return new Promise((resolve) => {
    const timeout = setTimeout(() => {
      const pending = pendingSnapshotRequests.get(requestId);
      if (!pending) {
        return;
      }
      pendingSnapshotRequests.delete(requestId);
      pending.resolve(null);
    }, PROJECT_SNAPSHOT_TIMEOUT_MS);

    pendingSnapshotRequests.set(requestId, {
      senderId: window.webContents.id,
      resolve,
      timeout,
    });

    window.webContents.send('project:request-snapshot', requestId);
  });
};

const applyProjectBundle = async (bundle: ProjectBundleV1): Promise<void> => {
  if (bundle.treeState) {
    await saveTreeState(bundle.treeState);
  }
  if (bundle.userSettings) {
    await saveUserSettings(bundle.userSettings);
  }

  const imageDir = getProjectImageAssetsDir();
  await mkdir(imageDir, { recursive: true });
  const existing = await readdir(imageDir, { withFileTypes: true });
  for (const entry of existing) {
    if (entry.isFile()) {
      await unlink(path.join(imageDir, entry.name));
    }
  }

  for (const image of bundle.images) {
    const normalized = normalizeRelativePath(image.relativePath).replace(/^[/\\]+/, '');
    const resolved = resolveImageAssetPath(normalized);
    if (!resolved) {
      continue;
    }
    const folderPath = path.dirname(resolved);
    await mkdir(folderPath, { recursive: true });
    const bytes = Buffer.from(image.dataBase64, 'base64');
    await writeFile(resolved, bytes);
  }
};

let activeProjectFilePath: string | null = null;

const emitProjectStatus = (
  window: BrowserWindow | null,
  payload: Omit<ProjectStatusPayload, 'at'>,
): void => {
  if (!window || window.isDestroyed()) {
    return;
  }
  const statusPayload: ProjectStatusPayload = {
    ...payload,
    at: Date.now(),
  };
  window.webContents.send('menu:project-status', statusPayload);
};

const saveProjectFileAs = async (): Promise<void> => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  if (!focusedWindow) {
    return;
  }

  const result = await dialog.showSaveDialog(focusedWindow, {
    title: 'Save Project File',
    defaultPath: activeProjectFilePath ?? path.join(getProjectRootPath(), 'untitled.testo'),
    filters: [{ name: 'Testo Project', extensions: ['testo'] }],
  });
  if (result.canceled || !result.filePath) {
    return;
  }

  try {
    await writeProjectBundle(result.filePath);
    activeProjectFilePath = result.filePath;
    emitProjectStatus(focusedWindow, {
      status: 'success',
      action: 'save-as',
      filePath: result.filePath,
      message: `Saved project as ${path.basename(result.filePath)}.`,
    });
  } catch (error: unknown) {
    emitProjectStatus(focusedWindow, {
      status: 'error',
      action: 'save-as',
      filePath: result.filePath,
      message: `Save As failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
    });
  }
};

const saveProjectFile = async (): Promise<void> => {
  if (!activeProjectFilePath) {
    await saveProjectFileAs();
    return;
  }
  const focusedWindow = BrowserWindow.getFocusedWindow();
  try {
    await writeProjectBundle(activeProjectFilePath);
    emitProjectStatus(focusedWindow, {
      status: 'success',
      action: 'save',
      filePath: activeProjectFilePath,
      message: `Saved ${path.basename(activeProjectFilePath)}.`,
    });
  } catch (error: unknown) {
    emitProjectStatus(focusedWindow, {
      status: 'error',
      action: 'save',
      filePath: activeProjectFilePath,
      message: `Save failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
    });
  }
};

const openProjectFile = async (): Promise<void> => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  if (!focusedWindow) {
    return;
  }

  const result = await dialog.showOpenDialog(focusedWindow, {
    title: 'Open Project File',
    properties: ['openFile'],
    filters: [{ name: 'Testo Project', extensions: ['testo'] }],
  });
  if (result.canceled || result.filePaths.length === 0) {
    return;
  }

  try {
    const filePath = result.filePaths[0];
    const bundle = await readProjectBundle(filePath);
    await applyProjectBundle(bundle);
    activeProjectFilePath = filePath;
    emitProjectStatus(focusedWindow, {
      status: 'success',
      action: 'open',
      filePath,
      message: `Opened ${path.basename(filePath)}.`,
    });
    focusedWindow.reload();
  } catch (error: unknown) {
    emitProjectStatus(focusedWindow, {
      status: 'error',
      action: 'open',
      message: `Open failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
    });
  }
};

const createNewProject = async (): Promise<void> => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  if (!focusedWindow) {
    return;
  }

  const result = await dialog.showMessageBox(focusedWindow, {
    type: 'question',
    buttons: ['Create New Project', 'Cancel'],
    defaultId: 1,
    cancelId: 1,
    title: 'Create New Project',
    message: 'Create a new project and clear the current local project data?',
    detail: 'This clears current tree, settings, and cached images for this workspace.',
  });

  if (result.response !== 0) {
    return;
  }

  try {
    await clearCurrentProjectData();
    activeProjectFilePath = null;
    emitProjectStatus(focusedWindow, {
      status: 'success',
      action: 'new',
      filePath: null,
      message: 'Created a new project workspace.',
    });
    focusedWindow.reload();
  } catch (error: unknown) {
    emitProjectStatus(focusedWindow, {
      status: 'error',
      action: 'new',
      filePath: null,
      message: `New project failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
    });
  }
};

ipcMain.handle('tree:load', async () => loadTreeState());
ipcMain.handle('tree:save', async (_event, state: PersistedTreeState) => {
  await saveTreeState(state);
});
ipcMain.handle('settings:load', async () => loadUserSettings());
ipcMain.handle('settings:save', async (_event, settings: UserSettings) => {
  await saveUserSettings(settings);
});
ipcMain.handle(
  'assets:save-image',
  async (
    _event,
    input: {
      bytes: Uint8Array;
      mimeType: string;
    },
  ) => saveImageAsset(input),
);
ipcMain.handle('assets:list-images', async () => listImageAssets());
ipcMain.handle('assets:delete-image', async (_event, relativePath: string) => {
  await deleteImageAsset(relativePath);
});
ipcMain.on(
  'project:snapshot-response',
  (
    event,
    payload:
      | {
          requestId?: unknown;
          snapshot?: unknown;
        }
      | undefined,
  ) => {
    if (!payload || typeof payload.requestId !== 'number') {
      return;
    }

    const pending = pendingSnapshotRequests.get(payload.requestId);
    if (!pending || pending.senderId !== event.sender.id) {
      return;
    }

    clearTimeout(pending.timeout);
    pendingSnapshotRequests.delete(payload.requestId);

    const snapshotCandidate = payload.snapshot as Partial<ProjectSnapshot> | null | undefined;
    if (
      snapshotCandidate &&
      typeof snapshotCandidate === 'object' &&
      typeof snapshotCandidate.treeState === 'object' &&
      snapshotCandidate.treeState !== null &&
      typeof snapshotCandidate.userSettings === 'object' &&
      snapshotCandidate.userSettings !== null
    ) {
      pending.resolve({
        treeState: snapshotCandidate.treeState as PersistedTreeState,
        userSettings: snapshotCandidate.userSettings as UserSettings,
      });
      return;
    }

    pending.resolve(null);
  },
);

const openSettingsFromMenu = (): void => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  if (!focusedWindow) {
    return;
  }
  focusedWindow.webContents.send('menu:open-settings');
};

const buildAppMenu = (): void => {
  const template: MenuItemConstructorOptions[] = [
    {
      label: 'File',
      submenu: [
        {
          label: 'New Project',
          accelerator: 'CmdOrCtrl+N',
          click: () => {
            void createNewProject();
          },
        },
        { type: 'separator' },
        {
          label: 'Open Project File...',
          accelerator: 'CmdOrCtrl+O',
          click: () => {
            void openProjectFile();
          },
        },
        {
          label: 'Save Project File',
          accelerator: 'CmdOrCtrl+S',
          click: () => {
            void saveProjectFile();
          },
        },
        {
          label: 'Save Project File As...',
          accelerator: 'CmdOrCtrl+Shift+S',
          click: () => {
            void saveProjectFileAs();
          },
        },
        { type: 'separator' },
        {
          label: 'Settings',
          accelerator: 'CmdOrCtrl+,',
          click: openSettingsFromMenu,
        },
        { type: 'separator' },
        { role: 'quit' },
      ],
    },
    { role: 'editMenu' },
    { role: 'viewMenu' },
    { role: 'windowMenu' },
    { role: 'help' },
  ];

  Menu.setApplicationMenu(Menu.buildFromTemplate(template));
};

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 1080,
    width: 1920,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  if (!app.isPackaged) {
    mainWindow.webContents.openDevTools();
  }
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  registerAssetProtocol();
  buildAppMenu();
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
