import {
  app,
  BrowserWindow,
  dialog,
  shell,
} from 'electron';
import { UpdateSourceType, updateElectronApp } from 'update-electron-app';
import path from 'node:path';
import type {
  LaunchState,
  PersistedTreeState,
  ProjectStatusPayload,
  SteamAchievementExportRequest,
  SteamAchievementExportResult,
  SteamMarketplaceExportRequest,
  SteamMarketplaceExportResult,
  UserSettings,
} from './shared/types';
import {
  ensureWritableWorkspaceRoot,
  getProjectImageAssetsDir,
  getProjectRootPath,
  getRecentProjectsPath,
  getTreeStatePath,
  getUserSettingsPath,
  getWindowIconPath,
  normalizeRelativePath,
} from './main/workspace-paths';
import { fileExists } from './main/json-file-store';
import {
  extractProjectFilePathFromArgv,
  LEGACY_PROJECT_EXTENSION,
  normalizeProjectFilePathCandidate,
  PRIMARY_PROJECT_EXTENSION,
} from './main/project-file-args';
import {
  compareVersions,
  fetchLatestGithubRelease,
  normalizeVersionTag,
  pickChecksumAssetForInstaller,
  pickWindowsInstallerAsset,
} from './main/update-utils';
import {
  downloadReleaseAsset,
  launchSilentWindowsInstaller,
  verifyDownloadedInstallerChecksum,
} from './main/windows-nsis-updater';
import { buildAppMenu } from './main/app-menu';
import { applyMacDockIcon, createMainWindow } from './main/window-factory';
import { registerIpcHandlers, type PendingSnapshotRequest } from './main/ipc-handlers';
import {
  deleteImageAsset as deleteImageAssetFromStore,
  listImageAssets as listImageAssetsFromStore,
  mimeTypeFromExtension,
  registerAssetProtocol as registerAssetProtocolHandler,
  registerAssetSchemePrivileges,
  resolveImageAssetPath as resolveImageAssetPathInStore,
  saveImageAsset as saveImageAssetToStore,
} from './main/image-assets';
import {
  clearCurrentProjectData as clearProjectDataFiles,
  loadTreeState as loadTreeStateFromFile,
  loadUserSettings as loadUserSettingsFromFile,
  removeFileIfExists,
  saveTreeState as saveTreeStateToFile,
  saveUserSettings as saveUserSettingsToFile,
} from './main/project-persistence';
import {
  type RecentProjectsFile,
  loadRecentProjectsState,
  saveRecentProjectsState,
} from './main/recent-projects';
import {
  exportCustomThemeToFile,
  importCustomThemeFromFile,
} from './main/theme-file';
import {
  applyProjectBundle,
  readProjectBundle,
  reloadSkippingSplashOnce,
  requestRendererProjectSnapshot,
  type ProjectBundleV1,
  writeProjectBundle,
} from './main/project-bundle';
import {
  getLaunchState as getLaunchStateFromStore,
  markProjectAsRecent as markProjectAsRecentInStore,
  removeRecentProject as removeRecentProjectFromStore,
} from './main/launch-state';
import { writeSteamAchievementExportSet } from './main/steam-achievement-export';
import { renderSteamAchievementEntryPngs } from './main/steam-achievement-image-renderer';
import { normalizeSteamAchievementArtData } from './features/steam-achievement/steam-achievement-art';
import { writeSteamMarketplaceExportSet } from './main/steam-marketplace-export';
import { renderSteamMarketplaceEntryPreset } from './main/steam-marketplace-image-renderer';
import { normalizeSteamMarketplaceAssetData } from './features/steam-marketplace/steam-marketplace-assets';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}
if (!app.requestSingleInstanceLock()) {
  app.quit();
}

const PROJECT_SNAPSHOT_TIMEOUT_MS = 1600;
const SKIP_SPLASH_QUERY_PARAM = 'skipSplashOnce';

let nextSnapshotRequestIdRef = 1;
const pendingSnapshotRequests = new Map<number, PendingSnapshotRequest>();
let pendingProjectOpenPath: string | null = null;

pendingProjectOpenPath = extractProjectFilePathFromArgv(process.argv);

registerAssetSchemePrivileges();

const loadRecentProjects = async (): Promise<RecentProjectsFile> =>
  loadRecentProjectsState(getRecentProjectsPath());

const saveRecentProjects = async (state: RecentProjectsFile): Promise<void> =>
  saveRecentProjectsState(getRecentProjectsPath(), state);

const saveImageAsset = async (input: { bytes: Uint8Array; mimeType: string }) =>
  saveImageAssetToStore(
    input,
    {
      getProjectImageAssetsDir,
      getProjectRootPath,
      normalizeRelativePath,
    },
    fileExists,
  );

const registerAssetProtocol = (): void =>
  registerAssetProtocolHandler({
    getProjectRootPath,
    normalizeRelativePath,
  });

const listImageAssets = async () =>
  listImageAssetsFromStore({
    getProjectImageAssetsDir,
    getProjectRootPath,
    normalizeRelativePath,
  });

const deleteImageAsset = async (relativePath: string): Promise<void> =>
  deleteImageAssetFromStore(relativePath, {
    getProjectImageAssetsDir,
    getProjectRootPath,
    normalizeRelativePath,
  });

const exportSteamAchievementSet = async (
  request: SteamAchievementExportRequest,
): Promise<SteamAchievementExportResult> => {
  const focusedWindow = BrowserWindow.getFocusedWindow() ?? mainWindowRef;
  if (!focusedWindow) {
    return {
      canceled: true,
      outputDir: null,
      exportedEntryCount: 0,
      skippedEntryCount: 0,
      writtenFileCount: 0,
    };
  }

  const presetLabel = request.data.presetId || 'steam-assets';
  const safeNodeName =
    [...request.nodeName.trim()]
      .map((character) =>
        character.charCodeAt(0) < 32 || /[<>:"/\\|?*]/.test(character) ? '-' : character,
      )
      .join('')
      .trim() || 'steam-achievements';
  const result = await dialog.showOpenDialog(focusedWindow, {
    title: 'Choose Export Folder',
    defaultPath: path.join(getProjectRootPath(), `${safeNodeName}-${presetLabel}`),
    properties: ['openDirectory', 'createDirectory'],
  });
  if (result.canceled || result.filePaths.length === 0) {
    return {
      canceled: true,
      outputDir: null,
      exportedEntryCount: 0,
      skippedEntryCount: 0,
      writtenFileCount: 0,
    };
  }

  const outputDir = result.filePaths[0];
  const normalizedRequest = {
    ...request,
    data: normalizeSteamAchievementArtData(request.data),
  };

  try {
    const exportResult = await writeSteamAchievementExportSet(
      {
        ...normalizedRequest,
        outputDir,
      },
      {
        resolveImageAssetPath,
        renderEntry: (entry, absolutePath) =>
          renderSteamAchievementEntryPngs(
            entry,
            absolutePath,
            normalizedRequest,
            resolveImageAssetPath,
          ),
      },
    );

    emitProjectStatus(focusedWindow, {
      status: exportResult.exportedEntryCount > 0 ? 'success' : 'info',
      action: 'export',
      filePath: outputDir,
      message:
        exportResult.exportedEntryCount > 0
          ? `Exported ${exportResult.exportedEntryCount} achievement image set${exportResult.exportedEntryCount === 1 ? '' : 's'} to ${path.basename(outputDir)}${exportResult.skippedEntryCount > 0 ? `; skipped ${exportResult.skippedEntryCount} invalid entr${exportResult.skippedEntryCount === 1 ? 'y' : 'ies'}` : ''}.`
          : `No achievement images were exported to ${path.basename(outputDir)}.`,
    });

    return exportResult;
  } catch (error: unknown) {
    emitProjectStatus(focusedWindow, {
      status: 'error',
      action: 'export',
      filePath: outputDir,
      message: `Achievement export failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
    });
    return {
      canceled: false,
      outputDir,
      exportedEntryCount: 0,
      skippedEntryCount: request.data.entries.length,
      writtenFileCount: 0,
    };
  }
};

const exportSteamMarketplaceAssets = async (
  request: SteamMarketplaceExportRequest,
): Promise<SteamMarketplaceExportResult> => {
  const focusedWindow = BrowserWindow.getFocusedWindow() ?? mainWindowRef;
  if (!focusedWindow) {
    return {
      canceled: true,
      outputDir: null,
      exportedEntryCount: 0,
      skippedEntryCount: 0,
      writtenFileCount: 0,
    };
  }

  const safeNodeName =
    [...request.nodeName.trim()]
      .map((character) =>
        character.charCodeAt(0) < 32 || /[<>:"/\\|?*]/.test(character) ? '-' : character,
      )
      .join('')
      .trim() || 'steam-marketplace-assets';
  const result = await dialog.showOpenDialog(focusedWindow, {
    title: 'Choose Export Folder',
    defaultPath: path.join(getProjectRootPath(), `${safeNodeName}-steam-marketplace-assets`),
    properties: ['openDirectory', 'createDirectory'],
  });
  if (result.canceled || result.filePaths.length === 0) {
    return {
      canceled: true,
      outputDir: null,
      exportedEntryCount: 0,
      skippedEntryCount: 0,
      writtenFileCount: 0,
    };
  }

  const outputDir = result.filePaths[0];
  const normalizedRequest = {
    ...request,
    data: normalizeSteamMarketplaceAssetData(request.data),
  };

  try {
    const exportResult = await writeSteamMarketplaceExportSet(
      {
        ...normalizedRequest,
        outputDir,
      },
      {
        renderEntryPreset: (entry, preset, output) =>
          renderSteamMarketplaceEntryPreset(
            entry,
            preset,
            output,
            normalizedRequest,
            resolveImageAssetPath,
          ),
      },
    );

    emitProjectStatus(focusedWindow, {
      status: exportResult.writtenFileCount > 0 ? 'success' : 'info',
      action: 'export',
      filePath: outputDir,
      message:
        exportResult.writtenFileCount > 0
          ? `Exported ${exportResult.writtenFileCount} Steam marketplace asset${exportResult.writtenFileCount === 1 ? '' : 's'} to ${path.basename(outputDir)}${exportResult.skippedEntryCount > 0 ? `; skipped ${exportResult.skippedEntryCount} invalid target${exportResult.skippedEntryCount === 1 ? '' : 's'}` : ''}.`
          : `No Steam marketplace assets were exported to ${path.basename(outputDir)}.`,
    });

    return exportResult;
  } catch (error: unknown) {
    emitProjectStatus(focusedWindow, {
      status: 'error',
      action: 'export',
      filePath: outputDir,
      message: `Steam marketplace export failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
    });
    return {
      canceled: false,
      outputDir,
      exportedEntryCount: 0,
      skippedEntryCount: normalizedRequest.data.entries.length,
      writtenFileCount: 0,
    };
  }
};

const resolveImageAssetPath = (relativePath: string): string | null =>
  resolveImageAssetPathInStore(relativePath, {
    getProjectImageAssetsDir,
    getProjectRootPath,
  });

const clearCurrentProjectData = async (): Promise<void> =>
  clearProjectDataFiles({
    treeStatePath: getTreeStatePath(),
    userSettingsPath: getUserSettingsPath(),
    imageAssetsDir: getProjectImageAssetsDir(),
  });

const loadTreeState = async (): Promise<PersistedTreeState | null> =>
  loadTreeStateFromFile(getTreeStatePath());

const saveTreeState = async (state: PersistedTreeState): Promise<void> =>
  saveTreeStateToFile(getTreeStatePath(), state);

const loadUserSettings = async (): Promise<UserSettings | null> =>
  loadUserSettingsFromFile(getUserSettingsPath());

const saveUserSettings = async (settings: UserSettings): Promise<void> =>
  saveUserSettingsToFile(getUserSettingsPath(), settings);

const getNextSnapshotRequestId = (): number => {
  const requestId = nextSnapshotRequestIdRef;
  nextSnapshotRequestIdRef += 1;
  return requestId;
};

const writeProjectBundleFile = async (filePath: string): Promise<void> =>
  writeProjectBundle(filePath, {
    loadTreeState,
    loadUserSettings,
    listImageAssets,
    mimeTypeFromExtension,
    requestRendererProjectSnapshot: async (window) =>
      requestRendererProjectSnapshot(window, {
        nextRequestId: getNextSnapshotRequestId,
        timeoutMs: PROJECT_SNAPSHOT_TIMEOUT_MS,
        pendingSnapshotRequests,
      }),
  });

const reloadWindowSkippingSplash = async (window: BrowserWindow): Promise<boolean> =>
  reloadSkippingSplashOnce(window, SKIP_SPLASH_QUERY_PARAM);

const applyImportedProjectBundle = async (bundle: ProjectBundleV1): Promise<void> =>
  applyProjectBundle(bundle, {
    saveTreeState,
    saveUserSettings,
    removeFileIfExists,
    getTreeStatePath,
    getUserSettingsPath,
    getProjectImageAssetsDir,
    normalizeRelativePath,
    resolveImageAssetPath,
  });

let activeProjectFilePath: string | null = null;
let mainWindowRef: BrowserWindow | null = null;

const FALLBACK_UPDATE_REPO_SLUG = 'nikoptp/TestoDesignSuite';
const UPDATE_REPO_SLUG = (process.env.TESTO_UPDATE_REPO ?? FALLBACK_UPDATE_REPO_SLUG).trim();
const DEFAULT_UPDATE_INTERVAL = '30 minutes';

const configureAutoUpdates = (): void => {
  if (!app.isPackaged) {
    return;
  }
  if (process.platform === 'win32') {
    return;
  }
  if (!UPDATE_REPO_SLUG) {
    return;
  }

  try {
    updateElectronApp({
      updateSource: {
        type: UpdateSourceType.ElectronPublicUpdateService,
        repo: UPDATE_REPO_SLUG,
      },
      updateInterval: DEFAULT_UPDATE_INTERVAL,
      notifyUser: true,
      logger: console,
    });
  } catch (error) {
    console.error(
      `Failed to configure automatic updates: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
};

const checkForGithubUpdates = async (manual: boolean): Promise<void> => {
  const currentVersion = normalizeVersionTag(app.getVersion());
  const focusedWindow = BrowserWindow.getFocusedWindow() ?? mainWindowRef;

  if (!UPDATE_REPO_SLUG) {
    if (manual) {
      emitProjectStatus(focusedWindow, {
        status: 'info',
        action: 'update',
        filePath: null,
        message:
          'Updates are not configured. Set TESTO_UPDATE_REPO to your GitHub repo (owner/name).',
      });
    }
    return;
  }

  try {
    const latest = await fetchLatestGithubRelease(
      UPDATE_REPO_SLUG,
      `${app.getName()}/${app.getVersion()}`,
    );
    const comparison = compareVersions(latest.latestVersion, currentVersion);

    if (comparison > 0) {
      emitProjectStatus(focusedWindow, {
        status: 'info',
        action: 'update',
        filePath: null,
        message: `Update available: v${latest.latestVersion} (current v${currentVersion}).`,
        updatePhase: 'available',
      });

      if (manual && focusedWindow) {
        const canRunWindowsInstallerUpdate = process.platform === 'win32' && app.isPackaged;
        const installerAsset = canRunWindowsInstallerUpdate
          ? pickWindowsInstallerAsset(latest.assets)
          : null;

        if (canRunWindowsInstallerUpdate && installerAsset) {
          const checksumAsset = pickChecksumAssetForInstaller(latest.assets, installerAsset);
          const result = await dialog.showMessageBox(focusedWindow, {
            type: 'info',
            buttons: ['Install Update', 'Open Download Page', 'Later'],
            defaultId: 0,
            cancelId: 2,
            title: 'Update Available',
            message: `Version ${latest.latestTag} is available.`,
            detail:
              `Current version: v${currentVersion}\n` +
              `Latest version: v${latest.latestVersion}\n` +
              `${checksumAsset ? 'Checksum verification: available' : 'Checksum verification: unavailable'}`,
          });

          if (result.response === 0) {
            try {
              emitProjectStatus(focusedWindow, {
                status: 'info',
                action: 'update',
                filePath: null,
                message: `Downloading installer (${installerAsset.name})...`,
                updatePhase: 'downloading',
                progressMode: 'indeterminate',
              });

              const updaterDir = path.join(app.getPath('userData'), 'updater');
              const downloadedInstaller = await downloadReleaseAsset({
                asset: installerAsset,
                userAgent: `${app.getName()}/${app.getVersion()}`,
                destinationDir: updaterDir,
              });

              if (checksumAsset) {
                emitProjectStatus(focusedWindow, {
                  status: 'info',
                  action: 'update',
                  filePath: null,
                  message: `Verifying installer checksum (${checksumAsset.name})...`,
                  updatePhase: 'verifying',
                  progressMode: 'indeterminate',
                });

                const downloadedChecksum = await downloadReleaseAsset({
                  asset: checksumAsset,
                  userAgent: `${app.getName()}/${app.getVersion()}`,
                  destinationDir: updaterDir,
                });
                await verifyDownloadedInstallerChecksum(
                  downloadedInstaller.localPath,
                  downloadedChecksum.localPath,
                );
              }

              emitProjectStatus(focusedWindow, {
                status: 'info',
                action: 'update',
                filePath: null,
                message: 'Installing update and restarting...',
                updatePhase: 'installing',
                progressMode: 'indeterminate',
              });

              await launchSilentWindowsInstaller(
                downloadedInstaller.localPath,
                app.getPath('exe'),
              );
              app.quit();
            } catch (error: unknown) {
              emitProjectStatus(focusedWindow, {
                status: 'error',
                action: 'update',
                filePath: null,
                message:
                  `Automatic install failed: ` +
                  `${error instanceof Error ? error.message : 'Unknown error'}`,
              });
            }
          } else if (result.response === 1) {
            await shell.openExternal(latest.downloadUrl);
          }
        } else {
          const result = await dialog.showMessageBox(focusedWindow, {
            type: 'info',
            buttons: ['Open Download Page', 'Later'],
            defaultId: 0,
            cancelId: 1,
            title: 'Update Available',
            message: `Version ${latest.latestTag} is available.`,
            detail: `Current version: v${currentVersion}\nLatest version: v${latest.latestVersion}`,
          });

          if (result.response === 0) {
            await shell.openExternal(latest.downloadUrl);
          }
        }
      }
      return;
    }

    if (manual) {
      emitProjectStatus(focusedWindow, {
        status: 'success',
        action: 'update',
        filePath: null,
        message: `You're on the latest version (v${currentVersion}).`,
      });
    }
  } catch (error: unknown) {
    if (!manual) {
      return;
    }

    emitProjectStatus(focusedWindow, {
      status: 'error',
      action: 'update',
      filePath: null,
      message: `Update check failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
    });
  }
};

const getLaunchState = async (): Promise<LaunchState> =>
  getLaunchStateFromStore({
    loadRecentProjects,
    saveRecentProjects,
    fileExists,
  });

const emitProjectStatus = (
  window: BrowserWindow | null,
  payload: Omit<ProjectStatusPayload, 'at'>,
): void => {
  if (!window || window.isDestroyed()) {
    return;
  }
  const statusPayload: ProjectStatusPayload = {
    ...payload,
    at: Date.now(),
  };
  window.webContents.send('menu:project-status', statusPayload);
};

const markProjectAsRecent = async (filePath: string): Promise<void> =>
  markProjectAsRecentInStore(filePath, {
    loadRecentProjects,
    saveRecentProjects,
  });

const removeRecentProject = async (filePath: string): Promise<void> =>
  removeRecentProjectFromStore(filePath, {
    loadRecentProjects,
    saveRecentProjects,
  });

const saveProjectFileAs = async (): Promise<boolean> => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  if (!focusedWindow) {
    return false;
  }

  const result = await dialog.showSaveDialog(focusedWindow, {
    title: 'Save Project File',
    defaultPath:
      activeProjectFilePath ?? path.join(getProjectRootPath(), `untitled.${PRIMARY_PROJECT_EXTENSION}`),
    filters: [
      {
        name: 'Testo Project',
        extensions: [PRIMARY_PROJECT_EXTENSION],
      },
    ],
  });
  if (result.canceled || !result.filePath) {
    return false;
  }

  try {
    await writeProjectBundleFile(result.filePath);
    activeProjectFilePath = result.filePath;
    await markProjectAsRecent(result.filePath);
    emitProjectStatus(focusedWindow, {
      status: 'success',
      action: 'save-as',
      filePath: result.filePath,
      message: `Saved project as ${path.basename(result.filePath)}.`,
    });
    return true;
  } catch (error: unknown) {
    emitProjectStatus(focusedWindow, {
      status: 'error',
      action: 'save-as',
      filePath: result.filePath,
      message: `Save As failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
    });
    return false;
  }
};

const saveProjectFile = async (): Promise<boolean> => {
  if (!activeProjectFilePath) {
    return saveProjectFileAs();
  }
  const focusedWindow = BrowserWindow.getFocusedWindow();
  try {
    await writeProjectBundleFile(activeProjectFilePath);
    await markProjectAsRecent(activeProjectFilePath);
    emitProjectStatus(focusedWindow, {
      status: 'success',
      action: 'save',
      filePath: activeProjectFilePath,
      message: `Saved ${path.basename(activeProjectFilePath)}.`,
    });
    return true;
  } catch (error: unknown) {
    emitProjectStatus(focusedWindow, {
      status: 'error',
      action: 'save',
      filePath: activeProjectFilePath,
      message: `Save failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
    });
    return false;
  }
};

const openProjectByPath = async (
  filePath: string,
  focusedWindow: BrowserWindow,
): Promise<boolean> => {
  try {
    await ensureWritableWorkspaceRoot();
    const bundle = await readProjectBundle(filePath);
    await applyImportedProjectBundle(bundle);
    activeProjectFilePath = filePath;
    await markProjectAsRecent(filePath);
    emitProjectStatus(focusedWindow, {
      status: 'success',
      action: 'open',
      filePath,
      message: `Opened ${path.basename(filePath)}.`,
    });
    const reloaded = await reloadWindowSkippingSplash(focusedWindow);
    if (!reloaded) {
      focusedWindow.reload();
    }
    return true;
  } catch (error: unknown) {
    await removeRecentProject(filePath);
    emitProjectStatus(focusedWindow, {
      status: 'error',
      action: 'open',
      filePath,
      message: `Open failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
    });
    return false;
  }
};

const focusMainWindow = (window: BrowserWindow | null): void => {
  if (!window || window.isDestroyed()) {
    return;
  }
  if (window.isMinimized()) {
    window.restore();
  }
  window.focus();
};

const openPendingProjectPath = (window: BrowserWindow): void => {
  if (!pendingProjectOpenPath) {
    return;
  }

  const filePath = pendingProjectOpenPath;
  pendingProjectOpenPath = null;
  void openProjectByPath(filePath, window);
};

app.on('second-instance', (_event, argv) => {
  const targetWindow = mainWindowRef;
  if (!targetWindow || targetWindow.isDestroyed()) {
    pendingProjectOpenPath = extractProjectFilePathFromArgv(argv) ?? pendingProjectOpenPath;
    return;
  }

  focusMainWindow(targetWindow);
  const incomingProjectPath = extractProjectFilePathFromArgv(argv);
  if (incomingProjectPath) {
    pendingProjectOpenPath = incomingProjectPath;
    openPendingProjectPath(targetWindow);
  }
});

app.on('open-file', (event, filePath) => {
  event.preventDefault();
  const normalized = normalizeProjectFilePathCandidate(filePath);
  if (!normalized) {
    return;
  }

  const targetWindow = mainWindowRef;
  if (!targetWindow || targetWindow.isDestroyed()) {
    pendingProjectOpenPath = normalized;
    return;
  }

  focusMainWindow(targetWindow);
  pendingProjectOpenPath = normalized;
  openPendingProjectPath(targetWindow);
});

const openProjectFile = async (): Promise<boolean> => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  if (!focusedWindow) {
    return false;
  }

  const result = await dialog.showOpenDialog(focusedWindow, {
    title: 'Open Project File',
    properties: ['openFile'],
    filters: [
      {
        name: 'Testo Project',
        extensions: [PRIMARY_PROJECT_EXTENSION, LEGACY_PROJECT_EXTENSION],
      },
    ],
  });
  if (result.canceled || result.filePaths.length === 0) {
    return false;
  }

  return openProjectByPath(result.filePaths[0], focusedWindow);
};

const openRecentProject = async (filePath: string): Promise<boolean> => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  if (!focusedWindow) {
    return false;
  }

  if (!filePath.trim()) {
    return false;
  }

  return openProjectByPath(filePath.trim(), focusedWindow);
};

const createNewProject = async (): Promise<boolean> => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  if (!focusedWindow) {
    return false;
  }

  const result = await dialog.showMessageBox(focusedWindow, {
    type: 'question',
    buttons: ['Create New Project', 'Cancel'],
    defaultId: 1,
    cancelId: 1,
    title: 'Create New Project',
    message: 'Create a new project and clear the current local project data?',
    detail: 'This clears current tree, settings, and cached images for this workspace.',
  });

  if (result.response !== 0) {
    return false;
  }

  try {
    await clearCurrentProjectData();
    activeProjectFilePath = null;
    await saveRecentProjects({
      ...(await loadRecentProjects()),
      lastActiveProjectPath: null,
    });
    emitProjectStatus(focusedWindow, {
      status: 'success',
      action: 'new',
      filePath: null,
      message: 'Created a new project workspace.',
    });
    const reloaded = await reloadWindowSkippingSplash(focusedWindow);
    if (!reloaded) {
      focusedWindow.reload();
    }
    return true;
  } catch (error: unknown) {
    emitProjectStatus(focusedWindow, {
      status: 'error',
      action: 'new',
      filePath: null,
      message: `New project failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
    });
    return false;
  }
};

registerIpcHandlers({
  loadTreeState,
  saveTreeState,
  loadUserSettings,
  saveUserSettings,
  saveImageAsset,
  listImageAssets,
  deleteImageAsset,
  exportSteamAchievementSet,
  exportSteamMarketplaceAssets,
  exportCustomThemeToFile,
  importCustomThemeFromFile,
  getLaunchState,
  openProjectFile,
  openRecentProject,
  createNewProject,
  checkForGithubUpdates,
  pendingSnapshotRequests,
});

const openSettingsFromMenu = (): void => {
  const focusedWindow = BrowserWindow.getFocusedWindow();
  if (!focusedWindow) {
    return;
  }
  focusedWindow.webContents.send('menu:open-settings');
};

const createWindow = (): BrowserWindow => {
  return createMainWindow({
    windowEntry: MAIN_WINDOW_WEBPACK_ENTRY,
    preloadEntry: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    windowIconPath: getWindowIconPath(),
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  applyMacDockIcon(getWindowIconPath());
  configureAutoUpdates();

  void (async () => {
    try {
      await ensureWritableWorkspaceRoot();
      const launchState = await getLaunchState();
      activeProjectFilePath = launchState.lastActiveProjectPath;
    } catch {
      activeProjectFilePath = null;
    }
    registerAssetProtocol();
    buildAppMenu({
      onNewProject: () => {
        void createNewProject();
      },
      onOpenProjectFile: () => {
        void openProjectFile();
      },
      onSaveProjectFile: () => {
        void saveProjectFile();
      },
      onSaveProjectFileAs: () => {
        void saveProjectFileAs();
      },
      onOpenSettings: openSettingsFromMenu,
      onCheckForUpdates: () => {
        void checkForGithubUpdates(true);
      },
    });
    mainWindowRef = createWindow();
    mainWindowRef.webContents.once('did-finish-load', () => {
      if (!mainWindowRef || mainWindowRef.isDestroyed()) {
        return;
      }
      openPendingProjectPath(mainWindowRef);
    });
    setTimeout(() => {
      void checkForGithubUpdates(false);
    }, 1200);
  })();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    mainWindowRef = createWindow();
    mainWindowRef.webContents.once('did-finish-load', () => {
      if (!mainWindowRef || mainWindowRef.isDestroyed()) {
        return;
      }
      openPendingProjectPath(mainWindowRef);
    });
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
